IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE ID = OBJECT_ID(N'TransliterationSystem'))
USE TransliterationSystem;

GO

IF OBJECT_ID('Alphabets', 'u') IS NULL
CREATE TABLE Alphabets
(
	SystemID INT IDENTITY(1, 1) PRIMARY KEY,
	SystemName NVARCHAR(50),
	RUS_A NVARCHAR(7),
	RUS_B NVARCHAR(7),
	RUS_V NVARCHAR(7),
	RUS_G NVARCHAR(7),
	RUS_D NVARCHAR(7),
	RUS_E NVARCHAR(7),
	RUS_YO NVARCHAR(7),
	RUS_ZH NVARCHAR(7),
	RUS_Z NVARCHAR(7),
	RUS_I NVARCHAR(7),
	RUS_J NVARCHAR(7),
	RUS_K NVARCHAR(7),
	RUS_L NVARCHAR(7),
	RUS_M NVARCHAR(7),
	RUS_N NVARCHAR(7),
	RUS_O NVARCHAR(7),
	RUS_P NVARCHAR(7),
	RUS_R NVARCHAR(7),
	RUS_S NVARCHAR(7),
	RUS_T NVARCHAR(7),
	RUS_U NVARCHAR(7),
	RUS_F NVARCHAR(7),
	RUS_KH NVARCHAR(7),
	RUS_C NVARCHAR(7),
	RUS_CH NVARCHAR(7),
	RUS_SH NVARCHAR(7),
	RUS_SHCH NVARCHAR(14),
	RUS_SolidSign NVARCHAR(7),
	RUS_Y NVARCHAR(7),
	RUS_SoftSign NVARCHAR(7),
	RUS_EH NVARCHAR(7),
	RUS_YU NVARCHAR(7),
	RUS_YA NVARCHAR(7)
)